server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password: Smartnj18@

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

resilience4j:
  circuitbreaker:
    instances:
      ACCOUNT-SERVICE:
        slidingWindowSize: 10
        failureRateThreshold: 50
