server:
  port: 8084

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:mysql://localhost:3306/transaction_db
    username: root
    password: Smartnj18@
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        group:
          enabled: true
      client:
        config:
          default:
            connectTimeout: 2000
            readTimeout: 3000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false


jwt:
  secret: ThisIsMySuperSecretKeyForBankingApplication12345678901234567890
  expiration: 86400000


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers


resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true

    instances:
      ACCOUNT-SERVICE:
        baseConfig: default

  timelimiter:
    configs:
      default:
        timeoutDuration: 3s

    instances:
      ACCOUNT-SERVICE:
        baseConfig: default

  retry:
    configs:
      default:
        maxAttempts: 3
        waitDuration: 200ms
        enableExponentialBackoff: true
        exponentialBackoffMultiplier: 2
        retryExceptions:
          - java.io.IOException
          - feign.RetryableException

    instances:
      ACCOUNT-SERVICE:
        baseConfig: default