server:
  port: 8080

spring:
  application:
    name: api-gateway

  config:
    import: "optional:configserver:http://localhost:8888"

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: customer-service
              uri: lb://CUSTOMER-SERVICE
              predicates:
                - Path=/api/customer/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: gatewayCustomer
                    fallbackUri: forward:/fallback/customer
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: SERVER_ERROR
                    statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE

            - id: account-service
              uri: lb://ACCOUNT-SERVICE
              predicates:
                - Path=/api/account/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: gatewayAccount
                    fallbackUri: forward:/fallback/account
                - name: Retry
                  args:
                    retries: 3
                    methods: GET
                    series: SERVER_ERROR
                    statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE

            - id: transaction-service
              uri: lb://TRANSACTION-SERVICE
              predicates:
                - Path=/api/transactions/**
              filters:
                - name: CircuitBreaker
                  args:
                    name: gatewayTransaction
                    fallbackUri: forward:/fallback/transaction
                - name: Retry
                  args:
                    retries: 3
                    methods: GET,POST
                    series: SERVER_ERROR
                    statuses: BAD_GATEWAY,SERVICE_UNAVAILABLE

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info,circuitbreakers

resilience4j:
  circuitbreaker:
    configs:
      default:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      gatewayCustomer:
        baseConfig: default
      gatewayAccount:
        baseConfig: default
      gatewayTransaction:
        baseConfig: default
  timelimiter:
    configs:
      default:
        timeoutDuration: 3s
    instances:
      gatewayCustomer:
        baseConfig: default
      gatewayAccount:
        baseConfig: default
      gatewayTransaction:
        baseConfig: default
